# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChatJY' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  pod 'Alamofire'
  # Pods for ChatJY

  target 'ChatJYTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChatJYUITests' do
    # Pods for testing
  end

end
